<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\DomainConfig\" />
    <Folder Include="Data\PatientIdentityRegistry\" />
    <Folder Include="Data\ValueSetRepository\" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="YamlDotNet" Version="16.3.0" />
		<PackageReference Include="EFCore.BulkExtensions" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\XcaInteropService.Commons\XcaInteropService.Commons.csproj" />
	</ItemGroup>

</Project>
